// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNCet5FtCiQ6aL_uZH78VoyGOoSZJC6kw',
    appId: '1:555612823997:web:9a4ec741dd5abfa4a772d4',
    messagingSenderId: '555612823997',
    projectId: 'counselling-project-11857',
    authDomain: 'counselling-project-11857.firebaseapp.com',
    storageBucket: 'counselling-project-11857.firebasestorage.app',
    measurementId: 'G-WXZXHE749B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxJbKBZIu9PNqXnwXY7uSIBJhboh7Joic',
    appId: '1:555612823997:android:c5676bde56bb07b9a772d4',
    messagingSenderId: '555612823997',
    projectId: 'counselling-project-11857',
    storageBucket: 'counselling-project-11857.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-0CY5nH3sQ9JIqq3JM7gdTiiFj0Ngiws',
    appId: '1:555612823997:ios:f7786ba4ad332a0fa772d4',
    messagingSenderId: '555612823997',
    projectId: 'counselling-project-11857',
    storageBucket: 'counselling-project-11857.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-0CY5nH3sQ9JIqq3JM7gdTiiFj0Ngiws',
    appId: '1:555612823997:ios:f7786ba4ad332a0fa772d4',
    messagingSenderId: '555612823997',
    projectId: 'counselling-project-11857',
    storageBucket: 'counselling-project-11857.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
}
